# Generated by Django 4.0.6 on 2022-07-06 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='event_duration',
            field=models.CharField(max_length=255),
        ),
    ]
