# Generated by Django 4.0.6 on 2022-08-01 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0003_businesstype_remove_ad_category_delete_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adinvitation',
            name='invitation_date',
        ),
        migrations.RemoveField(
            model_name='adinvitation',
            name='invitation_time',
        ),
        migrations.RemoveField(
            model_name='adinvitation',
            name='seen',
        ),
        migrations.AddField(
            model_name='adinvitation',
            name='seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='adinvitation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='Pending', max_length=20),
        ),
    ]
