# Generated by Django 4.0.6 on 2022-08-05 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0005_reservation'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='reservation',
            table='reservations',
        ),
    ]
