# Generated by Django 4.1 on 2022-08-10 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0007_alter_ad_description_alter_ad_total_shares_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adbannerimage',
            name='path',
        ),
        migrations.AddField(
            model_name='adbannerimage',
            name='image_path',
            field=models.FileField(blank=True, upload_to='banner/'),
        ),
    ]
