# Generated by Django 4.1 on 2022-08-10 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0008_remove_adbannerimage_path_adbannerimage_image_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adbannerimage',
            old_name='image_path',
            new_name='file_path',
        ),
    ]
