# Generated by Django 4.1 on 2022-08-10 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0009_rename_image_path_adbannerimage_file_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='adbanner',
            name='image_path',
            field=models.FileField(blank=True, null=True, upload_to='banners/'),
        ),
        migrations.DeleteModel(
            name='AdBannerImage',
        ),
    ]
