# Generated by Django 4.1 on 2022-08-11 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0010_adbanner_image_path_delete_adbannerimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adbanner',
            name='ad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adimage', to='commerce.ad'),
        ),
    ]
