# Generated by Django 4.1 on 2022-08-11 07:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0011_alter_adbanner_ad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adbanner',
            name='image_path',
            field=models.FileField(blank=True, null=True, upload_to='banners/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'mp4'])]),
        ),
    ]
