# Generated by Django 4.1 on 2022-08-11 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0012_alter_adbanner_image_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='business_sub_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ad_business_sub_type', to='commerce.businesstype'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='business_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ad_business_type', to='commerce.businesstype'),
        ),
    ]
