# Generated by Django 4.1 on 2022-08-11 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0013_ad_business_sub_type_alter_ad_business_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='business_sub_type',
        ),
        migrations.AddField(
            model_name='ad',
            name='business_sub_type',
            field=models.ManyToManyField(blank=True, null=True, related_name='ad_business_sub_type', to='commerce.businesstype'),
        ),
    ]
