# Generated by Django 4.1 on 2022-08-11 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0014_remove_ad_business_sub_type_ad_business_sub_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='business_sub_type',
            field=models.ManyToManyField(related_name='ad_business_sub_type', to='commerce.businesstype'),
        ),
    ]
