# Generated by Django 4.0.6 on 2022-08-15 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0015_alter_ad_business_sub_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesstype',
            name='icon',
            field=models.ImageField(blank=True, upload_to='icons/', verbose_name='Type Icon'),
        ),
    ]
