# Generated by Django 4.1 on 2022-09-07 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0018_adsave'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='alternative_suggestion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
