# Generated by Django 4.1 on 2022-09-07 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0019_reservation_alternative_suggestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='suggestion_status',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
