# Generated by Django 4.1 on 2022-09-08 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0020_reservation_suggestion_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='alternative_suggestion',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='suggestion_status',
        ),
    ]
