# Generated by Django 4.1 on 2022-09-09 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0022_remove_ad_container_ratio_alter_ad_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='num_of_guest',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
