# Generated by Django 4.1 on 2022-09-09 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0024_alter_reservation_num_of_guest'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='date_alt',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='has_alternavite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservation',
            name='marchant_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservation',
            name='table_alt',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='time_alt',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='user_approved',
            field=models.BooleanField(default=True),
        ),
    ]
