# Generated by Django 4.1 on 2022-09-09 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0025_reservation_date_alt_reservation_has_alternavite_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='marchant_approved',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='status',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='user_approved',
        ),
        migrations.AddField(
            model_name='reservation',
            name='marchant_status',
            field=models.CharField(blank=True, choices=[('pending', 'pending'), ('accepted', 'accepted'), ('rejected', 'rejected')], max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='user_status',
            field=models.CharField(blank=True, choices=[('pending', 'pending'), ('accepted', 'accepted'), ('rejected', 'rejected')], max_length=12, null=True),
        ),
    ]
