# Generated by Django 4.0.6 on 2022-09-09 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0026_remove_reservation_marchant_approved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='marchant_status',
            field=models.CharField(blank=True, choices=[('pending', 'pending'), ('accepted', 'accepted'), ('rejected', 'rejected')], default='pending', max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='user_status',
            field=models.CharField(blank=True, choices=[('pending', 'pending'), ('accepted', 'accepted'), ('rejected', 'rejected')], default='accepted', max_length=12, null=True),
        ),
    ]
