# Generated by Django 4.1 on 2022-09-12 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0027_alter_reservation_marchant_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='invited_guest',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
