# Generated by Django 4.1.1 on 2022-09-16 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0028_reservation_invited_guest'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesstype',
            name='business_group',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
