# Generated by Django 4.1.1 on 2022-09-16 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0024_alter_user_amenties'),
        ('commerce', '0029_businesstype_business_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='business_hour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.businesshour'),
        ),
        migrations.AddField(
            model_name='adinvitation',
            name='invite_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adinvitation',
            name='invite_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
