# Generated by Django 4.1.1 on 2022-09-16 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0031_remove_ad_business_hour_adbusinesshour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='event_days',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='event_duration',
        ),
        migrations.AddField(
            model_name='ad',
            name='event_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ad',
            name='event_start_date',
            field=models.DateField(blank=True, max_length=255, null=True),
        ),
    ]
