# Generated by Django 4.1 on 2022-08-08 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_reportreason'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='reason',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.reportreason'),
        ),
    ]
