# Generated by Django 4.0.6 on 2022-08-09 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_report_description_alter_report_reason'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='reportreason',
            table='reasons',
        ),
    ]
