# Generated by Django 4.1 on 2022-08-10 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_alter_reportreason_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.reportreason'),
        ),
    ]
