# Generated by Django 4.0.6 on 2022-08-16 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_alter_report_reason'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SavePostAd',
        ),
    ]
