# Generated by Django 4.0.6 on 2022-09-13 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0011_country_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='country_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
