# Generated by Django 4.1.1 on 2022-09-27 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0011_friends_blockfriends'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blockfriends',
            name='user',
        ),
        migrations.AddField(
            model_name='blockfriends',
            name='user',
            field=models.ManyToManyField(related_name='blocked_users', to='common.friends'),
        ),
    ]
