# Generated by Django 4.1.1 on 2022-09-16 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('commerce', '0001_initial'),
        ('auth', '0013_group_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='business_sub_type',
            field=models.ManyToManyField(related_name='user_business_sub_type', to='commerce.businesstype'),
        ),
        migrations.AddField(
            model_name='user',
            name='business_type',
            field=models.ManyToManyField(related_name='user_business_type', to='commerce.businesstype'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
