# Generated by Django 4.0.6 on 2022-08-09 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_user_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='business_phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='business_sub_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='business_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
