# Generated by Django 4.1 on 2022-08-11 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_user_business_phone_alter_user_business_sub_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='business_sub_type',
        ),
        migrations.RemoveField(
            model_name='user',
            name='business_type',
        ),
    ]
