# Generated by Django 4.1 on 2022-08-12 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0016_alter_user_business_sub_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reset_pass_otp',
            field=models.IntegerField(blank=True, max_length=6, null=True),
        ),
    ]
