# Generated by Django 4.1 on 2022-08-12 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0017_user_reset_pass_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='reset_pass_otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
