# Generated by Django 4.0.6 on 2022-08-15 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0015_alter_ad_business_sub_type'),
        ('authentication', '0018_alter_user_reset_pass_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='business_type',
        ),
        migrations.AddField(
            model_name='user',
            name='business_type',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_business_type', to='commerce.businesstype'),
        ),
    ]
