# Generated by Django 4.0.6 on 2022-08-15 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0015_alter_ad_business_sub_type'),
        ('authentication', '0019_remove_user_business_type_user_business_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='business_type',
            field=models.ManyToManyField(related_name='user_business_type', to='commerce.businesstype'),
        ),
    ]
