# Generated by Django 4.1 on 2022-08-18 10:24

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0013_group_active'),
        ('authentication', '0021_permission'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Permission',
        ),
        migrations.CreateModel(
            name='XzitPermission',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.permission',),
            managers=[
                ('objects', django.contrib.auth.models.PermissionManager()),
            ],
        ),
    ]
