# Generated by Django 4.0.5 on 2022-06-21 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_story_alter_postlike_table_storyviewer_postsave_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='views_count',
            field=models.IntegerField(default=0),
        ),
    ]
