# Generated by Django 4.0.6 on 2022-07-19 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0004_alter_story_views_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='story_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default=('video', 'Video'), max_length=10),
        ),
    ]
