# Generated by Django 4.0.6 on 2022-08-08 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0005_alter_story_story_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
