# Generated by Django 4.0.6 on 2022-08-09 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0006_post_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
