# Generated by Django 4.1 on 2022-08-10 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0008_alter_postimage_image_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimage',
            name='image_path',
            field=models.ImageField(upload_to='posts/'),
        ),
    ]
