# Generated by Django 4.1 on 2022-08-10 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0007_post_location'),
        ('activity', '0009_alter_postimage_image_path'),
    ]

    operations = [
    ]
