# Generated by Django 4.1 on 2022-08-10 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0011_alter_postimage_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image_url',
        ),
    ]
