# Generated by Django 4.1 on 2022-08-10 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0012_remove_post_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimage',
            name='image_path',
            field=models.FileField(upload_to='posts/'),
        ),
    ]
