# Generated by Django 4.1 on 2022-08-11 07:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0013_alter_postimage_image_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimage',
            name='image_path',
            field=models.FileField(upload_to='posts/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'mp4'])]),
        ),
    ]
