# Generated by Django 4.1 on 2022-08-11 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0015_alter_postcomment_post_alter_postimage_image_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postlike',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postlike', to='activity.post'),
        ),
    ]
