# Generated by Django 4.0.6 on 2022-08-12 14:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0016_alter_postlike_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='media',
            field=models.FileField(upload_to='stories/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'mp4'])]),
        ),
    ]
