# Generated by Django 4.1 on 2022-08-16 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0017_alter_story_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postsave',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postSave', to='activity.post'),
        ),
    ]
