# Generated by Django 4.1 on 2022-08-18 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0018_alter_postsave_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'permissions': [('like_create', 'Create Like')]},
        ),
    ]
