# Generated by Django 4.1 on 2022-08-18 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0019_alter_post_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
    ]
